stages:
    - build
    - deploy
build:
    stage: build
    tags:
        - futhark
        - todo
        - app
    script:
        - echo "Building package"
        - yarn install
        - yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
deploy_production:
    stage: deploy
    tags: 
        - futhark
        - todo
        - app
    script:
        - echo "Deploying to server"
        - cp -rv build/* /var/www/html/<destination_folder>/
        - echo "Deployed"
    environment:
        name: production
        url: 35.188.76.1
    only:
        - main